### ISSUE TITLE
Hello Schievel1

### ISSUE THREAD

**Issue by Nuralii1i** [Schievel1/Schievel1#2]
I didn't know how to reach you,so....sorry for taking your time
I am a beginner to Gentoo linux,and I like the editor lapce
I foud ver0.27 is released,and lapce ebuild in GURU is ver0.26 yet
So I am sencerely hoping you can update that(if you have time of course)
I am not a native English speaker,so plz don't mind if I said something incorrect

**Comment by Schievel1** [comment]
I will update it. Sorry, I'm a bit busy these days. 

Anyway, have you tried the 9999 package of it? It will install from the latest git commit of their repo.

**Comment by Nuralii1i** [comment]
> I will update it. Sorry, I'm a bit busy these days.
> 
> Anyway, have you tried the 9999 package of it? It will install from the latest git commit of their repo.

Thank you!
Yes I  tried that too,but installation failed,it is a little bit complex to explain,but I'll try,I can not directly connect Github where I live and it is not legal to use VPNs
So I use some mirrorsite of github or reversed proxies,unfortunately,portage don't use any of my variables(crates.io mirror,  .gitconfig,etc),so fetch fails everytime

I build one manually and installed it as an aur PKGBUILD told me
But I can install not 9999 one,so.....
Thank you again

**Comment by Schievel1** [comment]
Oh that's very unfortunate. 
Can you tell me what exactly you need to set to get it working outside portage? I can maybe bring this into a discussion at gentoo.

**Comment by Nuralii1i** [comment]
> Oh that's very unfortunate. Can you tell me what exactly you need to set to get it working outside portage? I can maybe bring this into a discussion at gentoo.
Hmmmm.....
Only thing I can't solve is,when I install something written in Rust(using portage),cargo fetch crates from github,there is a **~/.cargo/config** file to set proxy for crate.io ,but portage is not using that anyway
But I am leaving ,to somewhere else,I can use proxy to solve my network problems,then all problem will gone,I think
Honestly,I did not expect such a nice communication
Thank you

**Comment by Schievel1** [comment]
So when you install that software manually (by cloning the repo and downloading it or something and doing `cargo build` in there) it works and it fetches the crates from crates.io. But when you install that same package with portage, it will try to download the crates from github?

Btw, if you try to contact someone on github, one rather sneaky way is to look into the commit messages of people. They usually sign them with their email address. ;-)

/ I will bump the lapce package tomorrow, I promise.

**Comment by Nuralii1i** [comment]
> So when you install that software manually (by cloning the repo and downloading it or something and doing `cargo build` in there) it works and it fetches the crates from crates.io. But when you install that same package with portage, it will try to download the crates from github?
> 
> Btw, if you try to contact someone on github, one rather sneaky way is to look into the commit messages of people. They usually sign them with their email address. ;-)
> 
> / I will bump the lapce package tomorrow, I promise.

Sorry for late reply,got something to do on my job,so just have time to reply
Cargo problem is no longer a problem now(solved)
And understood,I'll try to send an email next time
I had a great time communicating with you.
Thank you very much for your teaching and sharing.
